name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^5.3.3
  table_calendar: ^3.0.9
  http: ^1.1.0
  intl: ^0.18.1
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  cookie_jar: ^4.0.8
  universal_html: ^2.2.4
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.14
  file_picker: ^6.1.1
  http_parser: ^4.0.2
  video_player: ^2.3.0
  pie_chart: ^5.1.0
  fl_chart: ^0.35.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

fonts:
  - family: PressStart2P
    fonts:
      - asset: assets/fonts/PressStart2P-Regular.ttf

  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/successful-sign.gif
    - assets/images/successfully-register.gif
    - assets/images/successfully-added.gif
    - assets/images/successfully-deleted.gif
    - assets/images/onboarding1.webp
    - assets/images/signin.gif
    - assets/images/no data.gif
    - assets/images/user-screen1.jpg
    - assets/images/user-screen2.jpg
    - assets/images/user-screen3.png
    - assets/images/user-screen4.jpg
    - assets/images/completion.gif
    