name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^5.3.3
  table_calendar: ^3.0.9
  http: ^1.1.0
  intl: ^0.18.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  cookie_jar: ^4.0.8
  universal_html: ^2.2.4
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.14
  http_parser: ^4.0.2
  video_player: ^2.3.0
  pie_chart: ^5.1.0
  fl_chart: ^0.35.0 
  webview_flutter: ^2.0.13
  youtube_player_flutter: ^9.0.0
  flutter_inappwebview: ^6.0.0
  image_picker: ^1.0.7
  cloudinary: ^1.2.0
  cloudinary_flutter: ^1.3.0
  cloudinary_sdk: ^5.0.0+1
  cached_network_image: ^3.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tinyAdvocateLogo.png"
  min_sdk_android: 21
    
  flutter_lints: ^2.0.0

fonts:
  - family: PressStart2P
    fonts:
      - asset: assets/fonts/PressStart2P-Regular.ttf

  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/successful-sign.gif
    - assets/images/successfully-register.gif
    - assets/images/successfully-added.gif
    - assets/images/successfully-deleted.gif
    - assets/images/onboarding1.webp
    - assets/images/signin.gif
    - assets/images/no data.gif
    - assets/images/user-screen1.jpg
    - assets/images/user-screen2.jpg
    - assets/images/user-screen3.png
    - assets/images/user-screen4.jpg
    - assets/images/completion.gif
    - assets/images/tinyAdvocateLogo.png
    - .env
    